name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install cmake libgtest-dev libbenchmark-dev -y
    - name: Configure build
      run: cmake -S . -B build
    - name: Build project
      run: cmake --build build

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install cmake libgtest-dev libbenchmark-dev -y
    - name: Configure build
      run: cmake -S . -B build
    - name: Build project
      run: cmake --build build
    - name: Run tests
      run: ctest --test-dir build

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install cmake libgtest-dev libbenchmark-dev -y
    - name: Configure build
      run: cmake -S . -B build
    - name: Build benchmarks
      run: cmake --build build
    - name: Run benchmarks
      run: ./build/benchmarks/benchmark_mathlib

  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - run: doxygen docs/Doxyfile
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./docs/html
